use crate::compliance_effectiveness::models::{
    current_quarter_bounds, previous_quarter_bounds, MetricFilters, QuarterlyEffectivenessReport,
    RealtimeComplianceKpis,
};
use crate::compliance_effectiveness::repository::ComplianceEffectivenessRepository;
use chrono::Utc;
use std::sync::Arc;
use uuid::Uuid;

pub struct ReportGenerationService {
    repo: Arc<ComplianceEffectivenessRepository>,
}

impl ReportGenerationService {
    pub fn new(repo: Arc<ComplianceEffectivenessRepository>) -> Self {
        Self { repo }
    }

    pub async fn dashboard_kpis(
        &self,
        filters: &MetricFilters,
    ) -> Result<RealtimeComplianceKpis, anyhow::Error> {
        let kpis = self.repo.compute_realtime_kpis(filters).await?;
        self.repo.upsert_hourly_snapshot(filters, &kpis).await?;
        Ok(kpis)
    }

    pub async fn generate_quarterly_report(
        &self,
        generated_by: &str,
    ) -> Result<QuarterlyEffectivenessReport, anyhow::Error> {
        let now = Utc::now();
        let (period_start, period_end) = previous_quarter_bounds(now);

        let filters = MetricFilters {
            corridor_id: None,
            user_tier: None,
            rule_set: None,
            asset_class: None,
            start_at: period_start,
            end_at: period_end,
        };

        let kpis = self.repo.compute_realtime_kpis(&filters).await?;
        let policy_effectiveness = self.repo.policy_effectiveness(&filters, 20).await?;
        let heatmap = self.repo.risk_heatmap(&filters).await?;
        let benchmarking = self.repo.benchmark_comparisons(&kpis).await?;
        let sar_trend = self.repo.sar_conversion_trend(12).await?;

        let mut policy_adjustments = Vec::new();
        for p in &policy_effectiveness {
            if p.noise_index > 1.2 {
                policy_adjustments.push(format!(
                    "Tune {} threshold/noise controls (noise_index={:.3})",
                    p.rule_name, p.noise_index
                ));
            }
        }

        if sar_trend.last().map(|s| s.deviation_alert).unwrap_or(false) {
            policy_adjustments.push(
                "Investigate SAR conversion deviation vs 6-month moving average".to_string(),
            );
        }

        let report = QuarterlyEffectivenessReport {
            id: Uuid::new_v4(),
            period_start,
            period_end,
            generated_at: Utc::now(),
            kpis,
            policy_effectiveness,
            heatmap,
            benchmarking,
            sar_trend,
            policy_adjustments,
        };

        self.repo
            .store_quarterly_report(period_start, period_end, generated_by, &report)
            .await?;

        Ok(report)
    }

    pub async fn ensure_quarterly_report_current(&self) -> Result<(), anyhow::Error> {
        let now = Utc::now();
        let (period_start, period_end) = previous_quarter_bounds(now);
        if !self
            .repo
            .quarterly_report_exists(period_start, period_end)
            .await?
        {
            let _ = self.generate_quarterly_report("system").await?;
        }
        Ok(())
    }

    pub async fn refresh_hourly_snapshot(&self) -> Result<(), anyhow::Error> {
        let now = Utc::now();
        let filters = MetricFilters {
            corridor_id: None,
            user_tier: None,
            rule_set: None,
            asset_class: None,
            start_at: now - chrono::Duration::days(30),
            end_at: now,
        };
        let kpis = self.repo.compute_realtime_kpis(&filters).await?;
        self.repo.upsert_hourly_snapshot(&filters, &kpis).await?;
        Ok(())
    }

    pub async fn ensure_current_quarter_baseline_report(&self) -> Result<(), anyhow::Error> {
        let now = Utc::now();
        let (period_start, period_end) = current_quarter_bounds(now);
        if !self
            .repo
            .quarterly_report_exists(period_start, period_end)
            .await?
        {
            // Store an in-progress baseline report under ad-hoc generation for visibility.
            // The full previous quarter report is still generated by ensure_quarterly_report_current.
            let _ = self.generate_quarterly_report("system").await?;
        }
        Ok(())
    }
}
